/**
 * Completely fictional data used when demo mode is active.
 * No real project names, no real employee names, no proprietary information.
 */

import type { Project, Risk } from './mock-data';

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'DEMO-TEC-01',
    name: 'ERP Modernisation',
    department: 'Technology',
    owner: 'Alex M.',
    status: 'In Progress',
    progress: 62,
    priority: 'High',
    startDate: '2026-01-15',
    targetDate: '2026-09-30',
    risks: 'Vendor delivery risk on integration module',
    objective: 'Migrate legacy ERP to cloud-native platform across all business units.',
    notes: 'Phase 1 (Finance) complete. Phase 2 (HR + Ops) in progress.',
    financials: { budget: 4200000, spent: 2600000 },
  },
  {
    id: 'DEMO-DIG-01',
    name: 'Customer Portal v2',
    department: 'Digital',
    owner: 'Sarah K.',
    status: 'In Progress',
    progress: 45,
    priority: 'Critical',
    startDate: '2026-02-01',
    targetDate: '2026-07-31',
    risks: 'UX research delayed by 2 weeks due to recruitment',
    objective: 'Redesign self-service portal with unified identity and real-time dashboards.',
    notes: 'Beta launch targeted Q3. Dependency on API Gateway (DEMO-TEC-03).',
    financials: { budget: 1800000, spent: 810000 },
  },
  {
    id: 'DEMO-TEC-02',
    name: 'Cloud Migration – Phase 2',
    department: 'Technology',
    owner: 'Raj P.',
    status: 'On Hold',
    progress: 28,
    priority: 'High',
    startDate: '2026-03-01',
    targetDate: '2026-12-31',
    risks: 'Pending security clearance blocking workload transfer',
    objective: 'Lift-and-shift on-premise workloads to multi-cloud (AWS + Azure).',
    notes: 'On hold pending security sign-off. Dependent on ERP Modernisation completion.',
    financials: { budget: 3500000, spent: 980000 },
  },
  {
    id: 'DEMO-STR-01',
    name: 'Sustainability Reporting Hub',
    department: 'Strategy',
    owner: 'Emma L.',
    status: 'In Progress',
    progress: 74,
    priority: 'Medium',
    startDate: '2025-10-01',
    targetDate: '2026-06-30',
    risks: 'Regulatory requirements may expand in scope',
    objective: 'Centralise ESG data collection and automate regulatory reporting.',
    notes: 'Data pipeline live. Regulatory submission due end of June.',
    financials: { budget: 650000, spent: 481000 },
  },
  {
    id: 'DEMO-TEC-03',
    name: 'API Gateway Rollout',
    department: 'Technology',
    owner: 'Li W.',
    status: 'Completed',
    progress: 100,
    priority: 'High',
    startDate: '2025-09-01',
    targetDate: '2026-03-31',
    risks: 'None',
    objective: 'Unified API gateway with rate-limiting, OAuth 2.0 and observability tooling.',
    notes: 'Successfully deployed March 2026. All services migrated.',
    financials: { budget: 950000, spent: 920000 },
  },
  {
    id: 'DEMO-HR-01',
    name: 'Workforce Analytics Platform',
    department: 'Human Resources',
    owner: 'Priya S.',
    status: 'Not Started',
    progress: 0,
    priority: 'Medium',
    startDate: '2026-07-01',
    targetDate: '2027-01-31',
    risks: 'Dependent on ERP data availability post-migration',
    objective: 'Real-time workforce capacity, attrition prediction, and skill-gap analytics.',
    notes: 'Kicks off Q3. Scoping workshop scheduled for July 2026.',
    financials: { budget: 1100000, spent: 0 },
  },
  {
    id: 'DEMO-COM-01',
    name: 'Loyalty Programme Revamp',
    department: 'Commercial',
    owner: 'Marcus T.',
    status: 'In Progress',
    progress: 55,
    priority: 'High',
    startDate: '2026-01-01',
    targetDate: '2026-08-31',
    risks: 'Partner API integration timelines uncertain',
    objective: 'Next-gen loyalty engine with personalised rewards and gamification.',
    notes: 'Tier structure finalised. Soft launch planned July 2026.',
    financials: { budget: 2300000, spent: 1265000 },
  },
  {
    id: 'DEMO-TEC-04',
    name: 'Cybersecurity Zero-Trust',
    department: 'Technology',
    owner: 'Raj P.',
    status: 'In Progress',
    progress: 38,
    priority: 'Critical',
    startDate: '2026-02-15',
    targetDate: '2026-11-30',
    risks: 'Unmanaged endpoint inventory larger than scoped',
    objective: 'Enterprise-wide zero-trust network access and identity perimeter hardening.',
    notes: 'Identity platform deployed. Network segmentation in progress.',
    financials: { budget: 2900000, spent: 1102000 },
  },
  {
    id: 'DEMO-STR-02',
    name: 'Data Governance Framework',
    department: 'Strategy',
    owner: 'Emma L.',
    status: 'In Progress',
    progress: 50,
    priority: 'Medium',
    startDate: '2025-11-01',
    targetDate: '2026-07-31',
    risks: 'Cross-department data ownership disputes',
    objective: 'Enterprise data catalogue, lineage tracking, and GDPR/PDPA compliance.',
    notes: 'Data catalogue published. Lineage mapping phase ongoing.',
    financials: { budget: 780000, spent: 390000 },
  },
  {
    id: 'DEMO-DIG-02',
    name: 'Mobile App Relaunch',
    department: 'Digital',
    owner: 'Sarah K.',
    status: 'Delayed',
    progress: 32,
    priority: 'High',
    startDate: '2026-01-20',
    targetDate: '2026-08-31',
    risks: 'App store policy review added 3-week delay',
    objective: 'Complete rebuild of consumer mobile app on React Native with offline-first architecture.',
    notes: 'Design system complete. Internal beta delayed to July.',
    financials: { budget: 1600000, spent: 512000 },
  },
];

export const DEMO_RISKS: Risk[] = [
  {
    id: 'DEMO-RISK-01',
    projectId: 'DEMO-TEC-01',
    description: 'Primary integration vendor flagged a 6-week delay on the finance module connector.',
    category: 'Vendor',
    impact: 'High',
    likelihood: 3,
    score: 12,
    severity: 'High',
    owner: 'Alex M.',
    mitigation: 'Engage secondary vendor as contingency; re-sequence dependent milestones.',
    status: 'Open',
    targetDate: '2026-07-31',
  },
  {
    id: 'DEMO-RISK-02',
    projectId: 'DEMO-DIG-02',
    description: 'New privacy manifest requirements may require additional development cycles.',
    category: 'Compliance',
    impact: 'Medium',
    likelihood: 4,
    score: 8,
    severity: 'Medium',
    owner: 'Sarah K.',
    mitigation: 'Allocate 2-week buffer for policy compliance; legal review in progress.',
    status: 'Open',
    targetDate: '2026-06-30',
  },
  {
    id: 'DEMO-RISK-03',
    projectId: 'DEMO-TEC-04',
    description: 'Expanding device inventory uncovered 340 unmanaged endpoints not in original scope.',
    category: 'Scope',
    impact: 'High',
    likelihood: 2,
    score: 6,
    severity: 'Medium',
    owner: 'Raj P.',
    mitigation: 'Phased onboarding: critical assets first, BYOD in Phase 3.',
    status: 'Closed',
    targetDate: '2026-05-31',
  },
];
