export interface Employee {
  id: string;
  name: string;
  email: string;
  department: string;
  userType: 'internal';
}

export const BIAL_EMPLOYEES: Employee[] = [
  { id: '103713', name: "Ajay Rao", email: 'ajay.rao@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '103466', name: "Ajinkya Mukund Jangale", email: 'ajinkya.m@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102268', name: "Akash Awasthi", email: 'akash.a@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '102532', name: "Akshata K U", email: 'akshata@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '102013', name: "Alphin Infant J", email: 'alphin.j@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103431', name: "Amit Vijay Paul", email: 'amit.paul@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103352', name: "Anand Viswanath", email: 'anand.v@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '102597', name: "Andrew Thomas", email: 'andrew@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '101579', name: "Anindita Sengupta", email: 'anindita@bialairport.com', department: 'CCO', userType: 'internal' },
  { id: '102325', name: "Ashish Bakshi", email: 'ashish.b@bialairport.com', department: 'BASL', userType: 'internal' },
  { id: '103767', name: "Ashish Sharma", email: 'ashish.s@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '102609', name: "Ashritha M C", email: 'ashritha@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103363', name: "Athira N Kaimal", email: 'athira.kn@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '102377', name: "Avinash B", email: 'avinash.b@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103587', name: "Avishek Das", email: 'avishek@bialairport.com', department: 'DutyFree', userType: 'internal' },
  { id: '101549', name: "Bhagawantham V", email: 'bhagawantham@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103522', name: "Bhupender Singh Rana", email: 'bhupender.r@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103519', name: "Deep Dabholkar", email: 'deep.d@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103334', name: "Deepika Dudeja", email: 'deepika.d@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103178', name: "Devayani Dorothy Vijayan", email: 'devayani@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '101681', name: "Dipti Gupta", email: 'dipti@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101814', name: "Dominic Devasia", email: 'dominic@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102745', name: "Durairaj M", email: 'durairaj@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103341', name: "George Bennet Kuruvilla", email: 'george.k@bialairport.com', department: 'BASL', userType: 'internal' },
  { id: '102809', name: "Ilora Ghosh Banerjee", email: 'ilora@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '103709', name: "Jatin Sharma", email: 'jatin.sharma@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103707', name: "Jesse Owance", email: 'jesse.owance@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103382', name: "Jitender Kallappa Dhule", email: 'jitender.k@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101410', name: "Jomy Augustin", email: 'jomy@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '100230', name: "Karthikeyan R", email: 'karthikeyan.r@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '102734', name: "Kaustuv Roy", email: 'kaustuv@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101657', name: "Kenneth Rosvang Guldbjerg", email: 'kenneth@bialairport.com', department: 'CCO', userType: 'internal' },
  { id: '103479', name: "Kiran Kumar B", email: 'kiran.bk@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103343', name: "Kiran Kumar B M", email: 'kiran.kb@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '103752', name: "Lakshmi Kumaresan", email: 'lakshmi.k@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103500', name: "Lingaraju BS", email: 'lingaraju.b@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103554', name: "Manjappa Gowda C S", email: 'manjappagowda.c@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102224', name: "Manjunath G", email: 'manjunath.g@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '103607', name: "Manoj Hodigere Somashekhrappa", email: 'manoj.hs@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102684', name: "Midhun Raveendranath", email: 'midhun@bialairport.com', department: 'DutyFree', userType: 'internal' },
  { id: '101604', name: "Mohammed Javeed", email: 'javeed@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102810', name: "Munegowda K V", email: 'munegowda@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102466', name: "Musthaq Ahamed", email: 'musthaq@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '102666', name: "Naveen Kumar C J", email: 'naveenkumar.cj@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102149', name: "Neeraj Manoria", email: 'neeraj.m@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '102754', name: "Neeraj Prakash", email: 'neeraj.p@bialairport.com', department: 'CCO', userType: 'internal' },
  { id: '103791', name: "Nikhil Goyal", email: 'nikhil.goyal@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '101474', name: "Noel Patrick Lewis", email: 'noel@bialairport.com', department: 'CCB', userType: 'internal' },
  { id: '101311', name: "Parameshwarayya A M", email: 'parameshwarayya@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '102923', name: "Prabhu U", email: 'prabhu@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103369', name: "Pradip Poria", email: 'pradip.p@bialairport.com', department: 'CCB', userType: 'internal' },
  { id: '103778', name: "Prashant Abraham", email: 'prashant.a@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '101587', name: "Pravat Kumar Paikray", email: 'pravat@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103585', name: "RAGHAVENDRA N", email: 'raghavendra.n@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '103443', name: "Raghavendra Patil", email: 'raghavendra.p@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103743', name: "Rohan Choudhury", email: 'rohan.c@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101241', name: "Sambasiva C", email: 'sambasiva@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101772', name: "Sampath Kumar J", email: 'sampath.k@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '103589', name: "Sandra Mariam Zachariah", email: 'sandra.zm@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '100893', name: "Sanjay Chandra B", email: 'sanjaychandra@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102744', name: "Sanjay Prasad", email: 'sanjay.prasad@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102636', name: "Sanketh S Nayak", email: 'sanketh@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '102590', name: "Sayantika Ghosh", email: 'sayantika@bialairport.com', department: 'Advertisment & Marketing', userType: 'internal' },
  { id: '103433', name: "Shankarendra M", email: 'shankarendra.m@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103698', name: "Sharath Srirama", email: 'sharath.s@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '103234', name: "Shardul Sidhu", email: 'shardul@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '102598', name: "Shiva Kumar K", email: 'shiva@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102192', name: "Shreedhar Babu R", email: 'shreedhar@bialairport.com', department: 'BASL', userType: 'internal' },
  { id: '103521', name: "SOMASHEKHARAPPA C. J.", email: 'somashekharappa@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103247', name: "Srikanth B", email: 'srikanth@bialairport.com', department: 'BASL', userType: 'internal' },
  { id: '101653', name: "Srikanth V", email: 'srikanth.v@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101314', name: "Stephen Alphonse Raj J", email: 'stephen@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103387', name: "Sunil Benni", email: 'sunil.benni@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103715', name: "Suresh Babu M V", email: 'suresh.mv@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '100849', name: "Syed Azhar Hassan", email: 'syedazhar@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '102661', name: "Syed Sameeruddin", email: 'syed.sameeruddin@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103742', name: "T S Praveen", email: 'praveen.t@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103798', name: "Vaibhav Mohan", email: 'vaibhav.mohan@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103811', name: "Vaishakh T", email: 'vaishakh@bialairport.com', department: 'DutyFree', userType: 'internal' },
  { id: '100484', name: "Vanishri A", email: 'vanishri@bialairport.com', department: 'Digital', userType: 'internal' },
  { id: '102735', name: "Vasudevamurthy H B", email: 'vasudevamurthy@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '800027', name: "Veeresh M A", email: 'veeresh.ma@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '101084', name: "Vinod M", email: 'vinod.m@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '102785', name: "Vinoth Kumar R", email: 'vinoth.kumar@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '103386', name: "Vipin Chengappa Konerira", email: 'vipin.c@bialairport.com', department: 'Operations', userType: 'internal' },
  { id: '800037', name: "Yamini Mahajan", email: 'yamini.mahajan@bialairport.com', department: 'Commercial Development', userType: 'internal' },
  { id: '102370', name: "Yogesha G G", email: 'yogesha.gg@bialairport.com', department: 'Operations', userType: 'internal' },
];

export const DEPARTMENTS = [
  'All Departments',
  'Operations',
  'Digital',
  'Commercial Development',
  'Advertisment & Marketing',
  'DutyFree',
  'CCO',
  'CCB',
  'BASL',
];

export function getEmployeeByEmail(email: string): Employee | undefined {
  return BIAL_EMPLOYEES.find(e => e.email.toLowerCase() === email.toLowerCase());
}

export function isInternalEmail(email: string): boolean {
  return email.toLowerCase().endsWith('@bialairport.com');
}
