// Auto-generated from BIAL_Dashboard_Final_V_Final.xlsx
// Contains all 142 projects and 10 risks from the BIAL Commercial Department
// Generated: 2026-05-14T10:24:37.279Z

export interface Project {
  id: string;
  name: string;
  department: string;
  owner: string;
  status: 'In Progress' | 'Not Started' | 'Completed' | 'Delayed' | 'On Hold';
  progress: number;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  startDate: string | null;
  targetDate: string | null;
  risks: string;
  objective: string;
  notes: string;
  // New fields
  projectDependencies?: string;  // IDs/names of projects this depends on
  supportTeam?: string;          // Support team members
  kpi?: string;                  // Key Performance Indicators for this project
  archived?: boolean;            // Soft-delete: true = moved to history
  archivedAt?: string;           // ISO timestamp when archived
}

export interface Risk {
  id: string;
  projectId: string;
  description: string;
  category: string;
  impact: 'High' | 'Medium' | 'Low';
  likelihood: number;
  score: number;
  severity: string;
  owner: string;
  mitigation: string;
  status: 'Open' | 'Closed';
  targetDate: string;
}

export interface Department {
  name: string;
  total: number;
  inProgress: number;
  completed: number;
  notStarted: number;
  delayed: number;
  critical: number;
  pctDone: number;
  color: string;
}

export const projects: Project[] = [
  {
    "id": "PRDIGI_01",
    "name": "DBS Bank Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with DBS bank and work on points conversion mechanism. DBS members have 20 Cr worth of points",
    "notes": ""
  },
  {
    "id": "PRDIGI_02",
    "name": "ITC Hotels Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with ITC hotels on rewards poitns conversion and coaliation partnership",
    "notes": ""
  },
  {
    "id": "PRDIGI_03",
    "name": "Payment Gateway Enhancement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-05-01",
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "Seasmless Payment experience by resolve all on going issues/Get new partner onboarded",
    "notes": ""
  },
  {
    "id": "PRDIGI_04",
    "name": "Airline partnership for Delayed Passenger Expereince",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "Data can not be shared due to GDPR complinace. This needs new product to scan boarding pass barcode and issue coupons.",
    "objective": "Onboard atleast one Airline to enhance delayed passneger expereince by Integrating Airline with Pulse rewards and replace existing coupon and manual F&B model",
    "notes": ""
  },
  {
    "id": "PRDIGI_05",
    "name": "Airline partnership for customer engagement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Partner with Airline to enhance customer engagment by curating personalised expereinces and offers to passengers",
    "notes": ""
  },
  {
    "id": "PRDIGI_06",
    "name": "CRM for Pulse Rewards Members",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "Build CRM strategies to enhance customer expereince of every rewards member by Launching multiple higher tier member. All CRM initiatives will be targeting expereinces not transactions.",
    "notes": ""
  },
  {
    "id": "PRDIGI_07",
    "name": "Gamification on Pusle",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "Build and launch multiple games on Pulse rewards to engage with Members",
    "notes": ""
  },
  {
    "id": "PRDIGI_08",
    "name": "Duty Free Click and Collect",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "Attrition, App stability in lownetwork zones",
    "objective": "Duty Free sales target through PULSE for FY26-27 is ₹8.3Cr. In order to drive this 3X growth, we need to drive as many projects as possible to hit this target",
    "notes": ""
  },
  {
    "id": "PRDIGI_09",
    "name": "Communication Standardisation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Utility guidelines, META and JIODLTS delivery rates",
    "objective": "Review and revamp the communications architecture flowing our of PULSE to our guest.",
    "notes": ""
  },
  {
    "id": "PRDIGI_10",
    "name": "MoEngage Trigger campaigns",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Promo msg delivery rates",
    "objective": "Identify cross selling and upselling opportunites based on Guest journey flows, through our CDEP Partner platform (Mo Engage)",
    "notes": ""
  },
  {
    "id": "PRDIGI_11",
    "name": "Hotel Data Reconciliation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "Operations heavy - Chance of manual errors high",
    "objective": "We have identified a large mismatch in reported Transit Hotel sales numbers and Actual Sales on ground.",
    "notes": ""
  },
  {
    "id": "PRDIGI_12",
    "name": "CBB Packages",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "Creating digital prepaid CBB++ Packages. Base of the package would be CBB and it can be paired with Lounge/Security Slot booking access/Misc other non-CBB products",
    "notes": ""
  },
  {
    "id": "PRDIGI_13",
    "name": "Hotels Channel Manager",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "Ops not following SOPs",
    "objective": "Automating orders coming from OTAs into the PMS and PULSE DB simultaneously",
    "notes": ""
  },
  {
    "id": "PRDIGI_14",
    "name": "AI Chatbot for Airport Navigation",
    "department": "Digital & Data",
    "owner": "",
    "status": "In Progress",
    "progress": 35,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-09-30",
    "risks": "LLM hallucination risk; need fallback routing",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDIGI_15",
    "name": "FINANCIALS \r\neSPP - 20",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PRDIGI_16",
    "name": "PULSE REWARD\r\n15,00,000 Active Members",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PRDIGI_17",
    "name": "PROCESS\r\nBuilding destination - NPS - 80",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time\r\n\r\nBLRPAY uptime",
    "notes": ""
  },
  {
    "id": "PRDIGI_18",
    "name": "GPTW - 85% for commercial",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PRDIGI_19",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  },
  {
    "id": "PROPR_01",
    "name": "BIAL Academy relaunch",
    "department": "Operations",
    "owner": "Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_02",
    "name": "Phase wise launch pf Parking guidance system on Pulse",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Delayed",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_03",
    "name": "ISO final certification process",
    "department": "Operations",
    "owner": "Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_04",
    "name": "FSTR by BLR Ordering at gates",
    "department": "Operations",
    "owner": "Digital owner/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_05",
    "name": "Ground transportation on CBB",
    "department": "Operations",
    "owner": "Ajay / Major",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_06",
    "name": "BLR Priority access",
    "department": "Operations",
    "owner": "Dominic / George Fanthome",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_07",
    "name": "Construction of additional BMTC zone",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_08",
    "name": "Bus canopy construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "Attrition, App stability in lownetwork zones",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_09",
    "name": "16m additional zone construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Utility guidelines, META and JIODLTS delivery rates",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_10",
    "name": "P7 re-designing with BCM exits",
    "department": "Operations",
    "owner": "Dominic / Projects team",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Promo msg delivery rates",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_11",
    "name": "MLCP at Alpha 4",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "Operations heavy - Chance of manual errors high",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_12",
    "name": "Fornightly hero products on social media - F&B",
    "department": "Operations",
    "owner": "Rohan / Prashanth",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_13",
    "name": "Fornightly hero products on social media - Retail",
    "department": "Operations",
    "owner": "Javeed / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "Ops not following SOPs",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_14",
    "name": "Fornightly hero products on social media - Landside",
    "department": "Operations",
    "owner": "Kiran / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_15",
    "name": "Namma Yatri final launch",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_16",
    "name": "Shoffer Pilot tracking / results",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_17",
    "name": "KIAF collection at Stores",
    "department": "Operations",
    "owner": "Prashanth / Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPR_18",
    "name": "Ground trasnportation to be integrated with Pulse",
    "department": "Operations",
    "owner": "Dominic / Neeraj/Devayani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_19",
    "name": "Smart Queue Management System",
    "department": "Operations",
    "owner": "Rohan Sharma",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-06-01",
    "targetDate": "2026-12-31",
    "risks": "Hardware procurement delays",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_20",
    "name": "FINANCIALS \r\nIPP 349\r\nSPP 1278",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PROPS_21",
    "name": "PULSE REWARD\r\n7,00,000 Active Members\r\nNPS - 80",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PROPS_22",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": ""
  },
  {
    "id": "PROPS_23",
    "name": "GPTW - 85% for commercial",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PROPS_24",
    "name": "KIAF - 1 cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  },
  {
    "id": "PROPS_25",
    "name": "NPS (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_26",
    "name": "Google Rating (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_27",
    "name": "Harvest Market",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "Delayed",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": "31st Mar 2026",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_28",
    "name": "PULSE - 145K active members",
    "department": "Operations",
    "owner": "Dominic / Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_29",
    "name": "Highfliers - to be revamped",
    "department": "Operations",
    "owner": "Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_30",
    "name": "Sustainability - Retail (Green zone)",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "31st Mar 2027",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_31",
    "name": "ASQ",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_32",
    "name": "SOS",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_33",
    "name": "Transfer Pax",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_34",
    "name": "BLR recommendations / BLR exclusives - communications & signages",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PROPS_35",
    "name": "Sustainability - Paperless billing",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_01",
    "name": "Store launches - 76 Store Onboarding - 122 (incl of 76)",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_02",
    "name": "Quad 1",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_03",
    "name": "T1 Refurbishment",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-10-15",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_04",
    "name": "ATMS",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-07-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_05",
    "name": "Dining facility @ T2 Basement",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Completed",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_06",
    "name": "MMTH",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-09-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_07",
    "name": "Onboarding and launching of all Pulse / Payment gateway / Loyalty on DAY 0 / EPOS / KIAF",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_08",
    "name": "TAT for Tender Process - 60 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_09",
    "name": "TAT for new store fitouts - 100 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_10",
    "name": "TAT for design development - 30 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_11",
    "name": "Project Management tool",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_12",
    "name": "Product Development (Water by Blr)",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-01-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_13",
    "name": "New product - 20 SKUs across gifting & destination merchandise",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_14",
    "name": "Brand Collaborations",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_15",
    "name": "New Brand Partnership Framework",
    "department": "Commercial Development",
    "owner": "Nikhil Gupta",
    "status": "In Progress",
    "progress": 60,
    "priority": "Critical",
    "startDate": "2026-02-01",
    "targetDate": "2026-07-31",
    "risks": "Legal review pending",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_16",
    "name": "FINANCIALS \r\nIPP XX\r\nSPP XXX",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_17",
    "name": "PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_18",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_19",
    "name": "GPTW - 85% for commercial",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PRCOMDEV_20",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  },
  {
    "id": "PRADV_01",
    "name": "Quad 1 Stage Tender Publish",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_02",
    "name": "Advertising Barricade Branding",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_03",
    "name": "Terminal 2 Immigration Asset Renewal",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_04",
    "name": "Lounge Survey RFQ",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_05",
    "name": "Terminal 2 Art Pavilion Commercial Evaluation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_06",
    "name": "Segmentation Study",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_07",
    "name": "BACL Advertising Strategy",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_08",
    "name": "Recycle Bags Eureka",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_09",
    "name": "Digital Content",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_10",
    "name": "KEMP Football -KIAF Framework",
    "department": "Advertising & Marketing",
    "owner": "Ilora/Anindita/Vani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_11",
    "name": "P4 Billboard Installation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRADV_14",
    "name": "Advertising SPP XXX (with a turnover of 216Cr - waiting for the number from Debashis)",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PRADV_13",
    "name": "Convert 300K temp users to active  Pulse Rewards users",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PRADV_15",
    "name": "GPTW - 85% for commercial",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PRADV_16",
    "name": "KIAF Funding - 1 Cr",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  },
  {
    "id": "PRDF_01",
    "name": "Financials - SPP - 964 (total pax) / IPP 385 (total pax)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_02",
    "name": "Introducing MAC cosmetics",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_03",
    "name": "Introducing new categories (Home appliances)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_04",
    "name": "KIAF donation (collection at Cash counter) - implementation on POS",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_05",
    "name": "PULSE - \"Click & Collect\" - to achieve 10 Cr for FY 26-27",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_06",
    "name": "PULSE - \"Click & Collect\" - Onboarding and maintaining 10 BAs",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_07",
    "name": "Marketing Support on Creatives for monthly campaigns",
    "department": "Duty Free",
    "owner": "Midhun",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_08",
    "name": "NPS - 80",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_09",
    "name": "AI Projects - Passenger led Promos",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_10",
    "name": "AI Projects - Heat Map",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_11",
    "name": "AI Projects - Smart Pricing compared to destination/origin Duty Free",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_12",
    "name": "PULSE Campaigns - DF X Cab Promotion",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_13",
    "name": "PULSE Campaigns - DF X Lounge Access (BASL)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_14",
    "name": "PULSE Campaigns - DF X SPA Access (BASL)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_15",
    "name": "Campaigns for transfer pax  - 9 nos.",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_16",
    "name": "New Store - LMS 2",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_17",
    "name": "New Store - Chanel",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_18",
    "name": "New Store - India Story",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_19",
    "name": "New Store - Tom Ford",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_20",
    "name": "New Store - Coty",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_21",
    "name": "New Store - Dior",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_22",
    "name": "P&C Campaigns - 10 no.s (staff Incentivised)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_23",
    "name": "Taj X Bengaluru DF Collaborated Offer",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_24",
    "name": "Pre-immigration DF / Pulse offer ads (Arr & Dep)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_25",
    "name": "Category Expert Badge & Certification (Motivating staffs)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_26",
    "name": "DF cross promo Offer with HMS outlets",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_27",
    "name": "DF is now Free Campaign",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRDF_28",
    "name": "FINANCIALS \r\nIPP ..\r\nSPP 817",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PRDF_29",
    "name": "DIGITAL / PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PRDF_30",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": ""
  },
  {
    "id": "PRDF_31",
    "name": "GPTW - 85% for commercial",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PRDF_32",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  },
  {
    "id": "PRCBB_01",
    "name": "Travel Concierge",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-07-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCBB_02",
    "name": "PRM Wheel chair ( B2c/B2b)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCBB_03",
    "name": "Paid premuim Buggy",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCBB_04",
    "name": "MHB Baggage Service (B2b/Airline)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCBB_05",
    "name": "Medical Tourism",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRCBB_06",
    "name": "Courier Service ( Excess Baggage)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_01",
    "name": "Flexi Space-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_02",
    "name": "Skydeck-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_03",
    "name": "Quad 080 Café- Concpet Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_04",
    "name": "T1 Celebrity Restaurant- Ideation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_05",
    "name": "Habitat-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_06",
    "name": "SPA Extension In T2 Intl SHA Design Development Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_07",
    "name": "T1 Mezzanine Lounge/F&B- Business Discovery & Mgt Approval Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_08",
    "name": "T2 South Indian Restaurant Kitchen @ Intl SHA Gate Z Café Menu Finalisation & Project Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_09",
    "name": "Urban Consolidation Centre - Central Kitchen / Bakery / Institute Ideation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_10",
    "name": "Forest Of Abundance -Project Execution & Business Evaluation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": ""
  },
  {
    "id": "PRBASL_11",
    "name": "FINANCIALS\r\nIPP 151\r\nSPP 415",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": ""
  },
  {
    "id": "PRBASL_12",
    "name": "PULSE REWARD\r\n100,000 Active Members\r\nNPS - 80",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": ""
  },
  {
    "id": "PRBASL_13",
    "name": "PROCESS\r\nLadies & Gentlemen serve Ladies & Gentlemen",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": ""
  },
  {
    "id": "PRBASL_14",
    "name": "GPTW - 90% for BASL",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": ""
  },
  {
    "id": "PRBASL_15",
    "name": "KIAF - INR 25,00,000\r\nSUSTAINABILITY - 10% reduction in food waste (0.40 gms per dpax)",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": ""
  }
];

export const risks: Risk[] = [
  {
    "id": "RSK-001",
    "projectId": "PRDIGI_01",
    "description": "ABC XYZ",
    "category": "Data/Technical",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-002",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Vendor/External",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-003",
    "projectId": "PRADV_03",
    "description": "ABC XYZ",
    "category": "Data Quality",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-004",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Compliance",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-005",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Governance",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-006",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "People/Culture",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-007",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Compliance",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-008",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Technical",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-009",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Resource",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-010",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Adoption",
    "impact": "Low",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  }
];

export const departments: Department[] = [
  { name: 'Digital & Data', total: 19, inProgress: 18, completed: 0, notStarted: 1, delayed: 0, critical: 6, pctDone: 0, color: '#5c7cfa' },
  { name: 'Operations', total: 35, inProgress: 22, completed: 0, notStarted: 11, delayed: 2, critical: 6, pctDone: 0, color: '#f59e0b' },
  { name: 'Commercial Development', total: 20, inProgress: 10, completed: 1, notStarted: 9, delayed: 0, critical: 1, pctDone: 5, color: '#10b981' },
  { name: 'Advertising & Marketing', total: 15, inProgress: 2, completed: 0, notStarted: 13, delayed: 0, critical: 0, pctDone: 0, color: '#8b5cf6' },
  { name: 'Duty Free', total: 32, inProgress: 0, completed: 0, notStarted: 32, delayed: 0, critical: 0, pctDone: 0, color: '#f97316' },
  { name: 'CBB & Lounge', total: 6, inProgress: 0, completed: 0, notStarted: 6, delayed: 0, critical: 0, pctDone: 0, color: '#ec4899' },
  { name: 'BASL', total: 15, inProgress: 0, completed: 0, notStarted: 15, delayed: 0, critical: 0, pctDone: 0, color: '#06b6d4' },
];

export const kpiSummary = {
  totalProjects: 142,
  inProgress: 52,
  completed: 1,
  delayed: 2,
  notStarted: 87,
  critical: 13,
  high: 119,
  medium: 5,
  low: 5,
  openRisks: 9,
  stuckProjects: 10,
  needsEscalation: 12,
  ownerBottlenecks: 7,
  totalRisks: 10,
  closedRisks: 1,
  highSeverityOpen: 0,
};

export const riskCategories = ['Data/Technical', 'Vendor/External', 'Data Quality', 'Compliance', 'Governance', 'People/Culture', 'Resource', 'Technical', 'Financial', 'Adoption'];

export const statusOptions = ['In Progress', 'Not Started', 'Completed', 'Delayed', 'On Hold'];
export const priorityOptions = ['Critical', 'High', 'Medium', 'Low'];

export const monthlyTrend = [
  { month: 'Oct', completed: 0, delayed: 0, inProgress: 28, newProjects: 12 },
  { month: 'Nov', completed: 0, delayed: 0, inProgress: 35, newProjects: 8 },
  { month: 'Dec', completed: 0, delayed: 1, inProgress: 38, newProjects: 5 },
  { month: 'Jan', completed: 0, delayed: 1, inProgress: 42, newProjects: 15 },
  { month: 'Feb', completed: 0, delayed: 1, inProgress: 45, newProjects: 10 },
  { month: 'Mar', completed: 1, delayed: 2, inProgress: 48, newProjects: 20 },
  { month: 'Apr', completed: 1, delayed: 2, inProgress: 50, newProjects: 18 },
  { month: 'May', completed: 1, delayed: 2, inProgress: 52, newProjects: 14 },
];

export const notifications = [
  { id: 1, title: 'Project Delayed', message: 'PROPR_02: Parking guidance system is now delayed', type: 'warning' as const, time: '2 hours ago', read: false },
  { id: 2, title: 'Risk Escalation', message: 'RSK-004: Compliance gap requires immediate attention', type: 'critical' as const, time: '3 hours ago', read: false },
  { id: 3, title: 'AI Insight', message: 'Digital & Data has 6 critical projects with 0% progress', type: 'insight' as const, time: '5 hours ago', read: false },
  { id: 4, title: 'Milestone Due', message: 'PRDIGI_03: Payment Gateway pilot due May 15', type: 'info' as const, time: '1 day ago', read: true },
  { id: 5, title: 'Owner Bottleneck', message: 'Musthaq Ahamed has 7 active projects assigned', type: 'warning' as const, time: '1 day ago', read: true },
];
