// Auto-generated from BIAL_Dashboard_Final_V_Final.xlsx
// Contains all 142 projects and 10 risks from the BIAL Commercial Department
// Generated: 2026-05-14T10:24:37.279Z

export interface Project {
  id: string;
  name: string;
  department: string;
  owner: string;
  status: 'In Progress' | 'Not Started' | 'Completed' | 'Delayed' | 'On Hold';
  progress: number;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  startDate: string | null;
  targetDate: string | null;
  risks: string;
  objective: string;
  notes: string;
  // New fields
  projectDependencies?: string;  // IDs/names of projects this depends on
  supportTeam?: string;          // Support team members
  kpi?: string;                  // Key Performance Indicators for this project
  archived?: boolean;            // Soft-delete: true = moved to history
  archivedAt?: string;           // ISO timestamp when archived
}

export interface Risk {
  id: string;
  projectId: string;
  description: string;
  category: string;
  impact: 'High' | 'Medium' | 'Low';
  likelihood: number;
  score: number;
  severity: string;
  owner: string;
  mitigation: string;
  status: 'Open' | 'Closed';
  targetDate: string;
}

export interface Department {
  name: string;
  total: number;
  inProgress: number;
  completed: number;
  notStarted: number;
  delayed: number;
  critical: number;
  pctDone: number;
  color: string;
}

export const projects: Project[] = [
  {
    "id": "PRDIGI_01",
    "name": "DBS Bank Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with DBS bank and work on points conversion mechanism. DBS members have 20 Cr worth of points",
    "notes": "In principal deal is closed and contract closure by 31st May.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_02",
    "name": "ITC Hotels Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with ITC hotels on rewards poitns conversion and coaliation partnership",
    "notes": "Initial discussion done, proposal is shared and waiting for revert from ITC.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_03",
    "name": "Payment Gateway Enhancement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-05-01",
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "Seasmless Payment experience by resolve all on going issues/Get new partner onboarded",
    "notes": "Pilot with new device will be implemented at DutyFree on 15th May.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_04",
    "name": "Airline partnership for Delayed Passenger Expereince",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "Data can not be shared due to GDPR complinace. This needs new product to scan boarding pass barcode and issue coupons.",
    "objective": "Onboard atleast one Airline to enhance delayed passneger expereince by Integrating Airline with Pulse rewards and replace existing coupon and manual F&B model",
    "notes": "Deatiled discussion has been done with AOC and this will need a new product to scan borading pass to enable coupon. This can not be integrated with Pulse due to unavailiability of passenger PI data.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_05",
    "name": "Airline partnership for customer engagement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Partner with Airline to enhance customer engagment by curating personalised expereinces and offers to passengers",
    "notes": "Proposal shared with Singapore Airlines and awaiting for their revert, Indigo discussion are at adnaved stage.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_06",
    "name": "CRM for Pulse Rewards Members",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "Build CRM strategies to enhance customer expereince of every rewards member by Launching multiple higher tier member. All CRM initiatives will be targeting expereinces not transactions.",
    "notes": "Proposal is ready to be discussed with leadership team in May, 2026 and finalize.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_07",
    "name": "Gamification on Pusle",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "Build and launch multiple games on Pulse rewards to engage with Members",
    "notes": "Launched \"Spin the Wheel\" in Pulse. Working on more games.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_08",
    "name": "Duty Free Click and Collect",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "Attrition, App stability in lownetwork zones",
    "objective": "Duty Free sales target through PULSE for FY26-27 is ₹8.3Cr. In order to drive this 3X growth, we need to drive as many projects as possible to hit this target",
    "notes": "Programm has started and progress is closely monitored.",
    "projectDependencies": "Avolta hiring speed",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_09",
    "name": "Communication Standardisation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Utility guidelines, META and JIODLTS delivery rates",
    "objective": "Review and revamp the communications architecture flowing our of PULSE to our guest.",
    "notes": "MoEngagae email warmup activity ahs started and shuld be completed by June end.",
    "projectDependencies": "Advertising and Performance Marketing team for Creatives (Copy + Art)",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_10",
    "name": "MoEngage Trigger campaigns",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Promo msg delivery rates",
    "objective": "Identify cross selling and upselling opportunites based on Guest journey flows, through our CDEP Partner platform (Mo Engage)",
    "notes": "Trigger campaigns ongoing, currently working on parking triggers by 20th May, 2026",
    "projectDependencies": "Advertising and Performance Marketing team for Creatives (Copy + Art)",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_11",
    "name": "Hotel Data Reconciliation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "Operations heavy - Chance of manual errors high",
    "objective": "We have identified a large mismatch in reported Transit Hotel sales numbers and Actual Sales on ground.",
    "notes": "Recon by May end. On ground SOPs to be conveyed and training to be carried out by May 2026.",
    "projectDependencies": "Elaachi Tech Team",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_12",
    "name": "CBB Packages",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "Creating digital prepaid CBB++ Packages. Base of the package would be CBB and it can be paired with Lounge/Security Slot booking access/Misc other non-CBB products",
    "notes": "Initial discussion done with GM. Internal meeting to discuss on development of this project.",
    "projectDependencies": "GM Tech/ Market research",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_13",
    "name": "Hotels Channel Manager",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "Ops not following SOPs",
    "objective": "Automating orders coming from OTAs into the PMS and PULSE DB simultaneously",
    "notes": "Scheduled for Q4",
    "projectDependencies": "ICT/Elaachi - integration with OTAs",
    "kpi": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_14",
    "name": "AI Chatbot for Airport Navigation",
    "department": "Digital & Data",
    "owner": "",
    "status": "In Progress",
    "progress": 35,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-09-30",
    "risks": "LLM hallucination risk; need fallback routing",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_15",
    "name": "FINANCIALS \r\neSPP - 20",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "⦁\tTurnover 50 cr (F&B XX, DF XX, Cab XX, Hotel XX, Lounge XX, CBB XX, PG XX)\r\n⦁\teSPP 20\r\n⦁\tAnalytics driven sales XX Cr (DF, Retail, F&B, Adv, Landisde)",
    "supportTeam": "⦁\tDevayani (performance marketing, activations)\r\n⦁\tDominic\r\n⦁\tDom, ABD, George",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_16",
    "name": "PULSE REWARD\r\n15,00,000 Active Members",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "⦁\tTotal PTD - 2 Mn, Active memebrs - 0.7 Mn\r\n⦁\tDF - 3.15 L\r\n⦁\tF&B - 8.63 L\r\n⦁\tLNG - 10 K\r\n⦁\tOnline - 5.48 L\r\n⦁\tRetail - 2.63 L\r\n⦁\tAll new vendors are on ePOS, rewards, PG, Pulse from day 1",
    "supportTeam": "⦁\tAvishek - for ops, Devayani for marketing\r\n⦁\tDominic for ops, Devayani for marketing\r\n⦁\tGeorge for ops, Devayani for marketing\r\n⦁\tDominic ops, Devayani for marketing\r\n⦁\tDominic ops, Devayani for marketing\r\n⦁\tPravat",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_17",
    "name": "PROCESS\r\nBuilding destination - NPS - 80",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time\r\n\r\nBLRPAY uptime",
    "notes": "",
    "kpi": "⦁\tNPS score - 80 (Pulse, F&B, 080, Retail, Landside commercial)\r\n⦁\tCoverage - 100%\r\n⦁\tService Recovery < 48 hrs\r\n⦁\tBLR Exclusive products in Pulse\r\n⦁\tContactless omni channel loune access\r\n⦁\tUnified Landside expereince (Alignment with AC, Commercial)\r\n⦁\tDriving Accountability - New goals/ Goals cascading XX%\r\n⦁\t99.98% uptime for valid transction on BLRPAY",
    "supportTeam": "⦁\tDom, Devayani, George\r\n⦁\tGeorge for ops, Devayani for marketing\r\n⦁\tPravat\r\n⦁\tPravat/George\r\n⦁\tCOO, Pravat, ABD, Rao (BACL), Master planning\r\n⦁\tAll",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_18",
    "name": "GPTW - 85% for commercial",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "2 Insipiration trips/conferences",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDIGI_19",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "⦁\tAuction platform\r\n⦁\tEnable 10 F&B and 5 retail stores for collecting KIAF",
    "supportTeam": "Dominic for ops",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_20",
    "name": "CBB - Offline Order Create",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-30",
    "risks": "Encryption Logic mismatch - Technical blocker (Saurabh)",
    "objective": "Walkin, B2B, EC Bookings via Pulse Offline order create webhook",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Noel",
    "projectDependencies": "CBB Tech / Gray Matter",
    "kpi": ""
  },
  {
    "id": "PRDIGI_21",
    "name": "CBB - Rewards for non Pulse",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "Pending Capex negotiation (Saurabh)",
    "objective": "Walkin, B2B, EC Rewards — event based",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Noel / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_22",
    "name": "CBB - Kiosk App",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "Pending Capex negotiation (Saurabh)",
    "objective": "Kiosk and Tablet builds for CBB",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Noel",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_23",
    "name": "Parking Phase 1",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-09-01",
    "targetDate": "2026-05-31",
    "risks": "",
    "objective": "Parking pre-ordering without status update webhook and without rewards",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Major",
    "projectDependencies": "Ski Data / Gateway",
    "kpi": ""
  },
  {
    "id": "PRDIGI_24",
    "name": "Pulse Xclusives",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-10-01",
    "targetDate": "2026-12-31",
    "risks": "Unplanned project — will require capex. Can be taken up only after trio project is implemented",
    "objective": "New pre-paid product for Premium Pulse membership — sell bundles combining products and services available on Pulse platform",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Ajay / Vani",
    "projectDependencies": "Seamless PG + Settlement Engine + Rewards on cart",
    "kpi": ""
  },
  {
    "id": "PRDIGI_25",
    "name": "Pulse Home Page Redesign",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "Design finalization delayed",
    "objective": "Home Page redesign — App, Mobile, Tablet, Kiosk and Desktop",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_26",
    "name": "Pulse Biz Page Redesign",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-08-31",
    "risks": "",
    "objective": "9 Biz Pages + 72 component pages — App, Mobile, Tablet, Kiosk and Desktop",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_27",
    "name": "Seamless Payment Gateway",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Enhance payment experience and reduce failure rates",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_28",
    "name": "Rewards Integration with Pulse Cart (Including Coupons)",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Unlock rewards coupons and merchant-funded promos",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_29",
    "name": "Pulse Seller Settlement Engine",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Simplify merchant settlement and enable merchant-funded promos",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_30",
    "name": "Pulse Promo Engine",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Enable cross-promotions and cart promotions",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_31",
    "name": "Transit Hotel Channel Manager",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-06-30",
    "risks": "",
    "objective": "Staff portal for offline order creation",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Ajay",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_32",
    "name": "DPDPA Compliance",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2027-01-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "Workshop required to scope product-level changes for DPDPA compliance",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh / Musthaq",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_33",
    "name": "My Booking Refactoring",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-05-31",
    "risks": "",
    "objective": "Upgrade UI and provide all relevant booking information to users",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PRDIGI_34",
    "name": "WhatsApp Commerce",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "Under exploration",
    "objective": "Enable Pulse commerce flows using WhatsApp",
    "notes": "Reporting Manager: Neeraj Manoria",
    "supportTeam": "Saurabh",
    "projectDependencies": "",
    "kpi": ""
  },
  {
    "id": "PROPR_01",
    "name": "BIAL Academy relaunch",
    "department": "Operations",
    "owner": "Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "",
    "notes": "RFQ has been rolled out, go live 11th May.\r\nTechnical eval and new aggreemnt by 30th June.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_02",
    "name": "Phase wise launch pf Parking guidance system on Pulse",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Delayed",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_03",
    "name": "ISO final certification process",
    "department": "Operations",
    "owner": "Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_04",
    "name": "FSTR by BLR Ordering at gates",
    "department": "Operations",
    "owner": "Digital owner/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_05",
    "name": "Ground transportation on CBB",
    "department": "Operations",
    "owner": "Ajay / Major",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_06",
    "name": "BLR Priority access",
    "department": "Operations",
    "owner": "Dominic / George Fanthome",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_07",
    "name": "Construction of additional BMTC zone",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_08",
    "name": "Bus canopy construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "Attrition, App stability in lownetwork zones",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_09",
    "name": "16m additional zone construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Utility guidelines, META and JIODLTS delivery rates",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_10",
    "name": "P7 re-designing with BCM exits",
    "department": "Operations",
    "owner": "Dominic / Projects team",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "META Promo msg delivery rates",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_11",
    "name": "MLCP at Alpha 4",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "Operations heavy - Chance of manual errors high",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_12",
    "name": "Fornightly hero products on social media - F&B",
    "department": "Operations",
    "owner": "Rohan / Prashanth",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_13",
    "name": "Fornightly hero products on social media - Retail",
    "department": "Operations",
    "owner": "Javeed / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "Ops not following SOPs",
    "objective": "",
    "notes": "WIP and go live on 3rd week of May.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_14",
    "name": "Fornightly hero products on social media - Landside",
    "department": "Operations",
    "owner": "Kiran / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_15",
    "name": "Namma Yatri final launch",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_16",
    "name": "Shoffer Pilot tracking / results",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_17",
    "name": "KIAF collection at Stores",
    "department": "Operations",
    "owner": "Prashanth / Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "24 Stores are active and collection are in progress.",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPR_18",
    "name": "Ground trasnportation to be integrated with Pulse",
    "department": "Operations",
    "owner": "Dominic / Neeraj/Devayani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_19",
    "name": "Smart Queue Management System",
    "department": "Operations",
    "owner": "Rohan Sharma",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-06-01",
    "targetDate": "2026-12-31",
    "risks": "Hardware procurement delays",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_20",
    "name": "FINANCIALS \r\nIPP 349\r\nSPP 1278",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "⦁\tSPP - 1278\r\n⦁\tIPP - 349\r\n⦁\tATV - 1389\r\n⦁\tPent% - 92%",
    "supportTeam": "⦁\tPravat Dev & Neeraj- Store Opening to be inline with the Business plan.\r\n⦁\tLandside Security: Keep the Terminals Free of Touts / unauthorised operators ( Authorised Partner Feedback- Via Survey of 10 sample days / Month)\r\n⦁\t2 parking campaigns to increase penetration by 1% over the baseline- DV.",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_21",
    "name": "PULSE REWARD\r\n7,00,000 Active Members\r\nNPS - 80",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "⦁\tFSTR Revenue Generation - 10% YOY\r\n⦁\tNPS - 100% Coverage Retail & F&B\r\n⦁\tService Recovery less then 48hrs detactors\r\n⦁\tGoogle Rating -4.80\r\n⦁\tASQ - 4.65\r\n⦁\tPartner Feedback > 4.2",
    "supportTeam": "Neeraj & Team",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_22",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "kpi": "⦁\tTransfer e-vouchers issued to >10% of all transfer passengers with a minimum redemption rate of 2% \r\n⦁\tPULSE Rollout: \r\n⦁\tBial Academy - 100% activation & 80% usage\r\n⦁\t10 new modules\r\n⦁\tParking 2.0 Rollout on Pulse/ Physical\r\n⦁\tISO Survellience Audit",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_23",
    "name": "GPTW - 85% for commercial",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "⦁\tTraining - 5 days\r\n⦁\tGender : 70:30 \r\n⦁\tInspirational Trips - 2",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_24",
    "name": "KIAF - 1 cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Operations",
    "owner": "Dominic",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "⦁\t1cr for KIAF\r\n⦁\tCumulative CO₂ savings of 4575 tons achieved by Mar'27\r\n⦁\tFood Waste Reduction - 0.083grm per Dpax\r\n⦁\t30% Reduction in bills printing over LY Baseline\r\n⦁\tDrive Collective event at KIAF Schools / NGOs\r\n⦁\tIncrease Plastic-to-glass bottle sales ratio by ≥ 10%",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_25",
    "name": "NPS (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Reported on 11th May - NPS is 87.42",
    "supportTeam": "Akash",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_26",
    "name": "Google Rating (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "As on date 4.85",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_27",
    "name": "Harvest Market",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "Delayed",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": "31st Mar 2026",
    "risks": "",
    "objective": "",
    "notes": "Schedule in place, approval pending from Procurement",
    "supportTeam": "Akash / Akshata",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_28",
    "name": "PULSE - 145K active members",
    "department": "Operations",
    "owner": "Dominic / Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "As on date xxxx",
    "supportTeam": "Musthaq/ Ajay",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_29",
    "name": "Highfliers - to be revamped",
    "department": "Operations",
    "owner": "Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "To work on the plan for this FY as per CCO's feedback",
    "supportTeam": "Vaibhav/Prabhu/ Musthaq/Andrew",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_30",
    "name": "Sustainability - Retail (Green zone)",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "31st Mar 2027",
    "risks": "",
    "objective": "",
    "notes": "Should start by Jun 2026",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PROPS_31",
    "name": "ASQ",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "ACI has asked for -I commercial survey at dep gates",
    "supportTeam": "Rohan/lounge team",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_32",
    "name": "SOS",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Plan to be finalised by Jule 26 end",
    "supportTeam": "Mktng / Digital team",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_33",
    "name": "Transfer Pax",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Pending for approval - ?",
    "supportTeam": "Mktng / Digital team",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_34",
    "name": "BLR recommendations / BLR exclusives - communications & signages",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Pending from marketing team",
    "supportTeam": "Akshata / Devayani / Neeraj",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_35",
    "name": "Sustainability - Paperless billing",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "supportTeam": "Akash / Neeraj",
    "kpi": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_01",
    "name": "Store launches - 76 Store Onboarding - 122 (incl of 76)",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_02",
    "name": "Quad 1",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_03",
    "name": "T1 Refurbishment",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-10-15",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_04",
    "name": "ATMS",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-07-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_05",
    "name": "Dining facility @ T2 Basement",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Completed",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_06",
    "name": "MMTH",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-09-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_07",
    "name": "Onboarding and launching of all Pulse / Payment gateway / Loyalty on DAY 0 / EPOS / KIAF",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_08",
    "name": "TAT for Tender Process - 60 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_09",
    "name": "TAT for new store fitouts - 100 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_10",
    "name": "TAT for design development - 30 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_11",
    "name": "Project Management tool",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_12",
    "name": "Product Development (Water by Blr)",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-01-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_13",
    "name": "New product - 20 SKUs across gifting & destination merchandise",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_14",
    "name": "Brand Collaborations",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_15",
    "name": "New Brand Partnership Framework",
    "department": "Commercial Development",
    "owner": "Nikhil Gupta",
    "status": "In Progress",
    "progress": 60,
    "priority": "Critical",
    "startDate": "2026-02-01",
    "targetDate": "2026-07-31",
    "risks": "Legal review pending",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCOMDEV_16",
    "name": "FINANCIALS \r\nIPP XX\r\nSPP XXX",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "⦁\tTurnover from New Commercial Concepts XX Cr for the Year FY 27 \r\n⦁\t(SPP @ XXX, IPP @ XXX)\r\n⦁\tNew Contract Value (MAG) from Partner Onboarding at BLR Airport - XX Cr  in FY27.  \r\n⦁\t(SPP @ XXX, IPP @ XXX)\r\n⦁\tInvestment commitment from new Partners\r\n⦁\t (SPP @ XXX, IPP @ XXX)\r\n⦁\t2 New Concession Contracts beyond BLR\r\n⦁\tCBB Revenue \r\n⦁\t(SPP @ XXX, IPP @ XXX)",
    "supportTeam": "Project Department (CPO Ravi)\r\n-\r\n-\r\nGeorge & Ashish\r\nCOO, Dedicated M&A access",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_17",
    "name": "PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "⦁\t100% Onboarding of New Stores to Digital Platforms on Day 0 (Loyalty, PG, KIAF and ePOS Agreement to be live on Day 0 of New Store Opening)\r\n⦁\tIntroduction of NPS for CBB. Target NPS of 70\r\n⦁\tOnboarding of 7 Anchor Brands \r\n⦁\t( DF-Dior, DF-Tom Ford, DF-Armani, DF-CoTY, DF-Swarovski, DF-Lux Fashion, Gordon Ramsey, MM x Ranveer Brar) \r\n⦁\tLaunch of 80+7 New Concepts for the Year FY 26-27\r\n⦁\tT1-48,\r\n⦁\tT2-12,\r\n⦁\tQuad-6,\r\n⦁\tMMTH-9,\r\n⦁\tATMS-7.\r\n⦁\tPop-Up - 7 Nos\r\n⦁\tLaunch of New Products - Water, Home Fragrance, Gifting Solutions, Tea/Coffee, Chocolates ( 25 SKUs).",
    "supportTeam": "Neeraj\r\nNeeraj\r\nAvishek\r\nProject Department (CPO Ravi)\r\nGeorge, Dominic",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_18",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "kpi": "⦁\tTAT for Tender Process - 60 Days\r\n⦁\tTAT for New Store Fit-outs - 100 Days\r\n⦁\tTAT for Design Development- 30 Days\r\n⦁\tLaunch of Commercial Project Management Tool by Jun-26\r\n⦁\tHosting 4 Brand Launch Events\r\n⦁\tLaunch of BLR Contactless Lounge Access Program by Feb-27\r\n⦁\t2 banks to be onboarded",
    "supportTeam": "Devyani, Avishek, Ilora, Anu\r\n                                                                                                                                                                                                                                                              \r\nNeeraj, Jeune, Ashish, George",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_19",
    "name": "GPTW - 85% for commercial",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "⦁\tAttending 3 Global Conferences\r\n⦁\tSpeaking at 3 Global Conferences\r\n⦁\tVisting 3 Intl. Airports for Inspiration\r\n⦁\tSelf Development - 80 Training Hours \r\n⦁\tALP Project Exceution - BIAL Academy.\r\n⦁\tCompletion of Assigned / Recommended IDP - 360 Feedback / Books \r\n⦁\tUpskilling/Development Courses",
    "supportTeam": "Dr. Devasia & Gp. Capt. Srinivas",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_20",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "⦁\t20 Lac Contribution from New Partners for KIAF Trust\r\n⦁\tKIAF Contribution - Re1/Water Bottle sold, Rs5/Product (own brand) Sold\r\n⦁\tMin. 70% LEED Certified Materials for New Stores / Min. 10% for RRR for New Stores\r\n⦁\tGender Diversity at New Outlets - Females Ratio min. 30%\r\n⦁\t1 PRM Staff for every New Store (Enable India)",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_01",
    "name": "Quad 1 Stage Tender Publish",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_02",
    "name": "Advertising Barricade Branding",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_03",
    "name": "Terminal 2 Immigration Asset Renewal",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_04",
    "name": "Lounge Survey RFQ",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_05",
    "name": "Terminal 2 Art Pavilion Commercial Evaluation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_06",
    "name": "Segmentation Study",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_07",
    "name": "BACL Advertising Strategy",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_08",
    "name": "Recycle Bags Eureka",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_09",
    "name": "Digital Content",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_10",
    "name": "KEMP Football -KIAF Framework",
    "department": "Advertising & Marketing",
    "owner": "Ilora/Anindita/Vani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_11",
    "name": "P4 Billboard Installation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_14",
    "name": "Advertising SPP XXX (with a turnover of 216Cr - waiting for the number from Debashis)",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "⦁\tBuilding 3 marquee properties\r\n⦁\tGTM strategy plan to get 6 sponsors on board\r\n⦁\tA system where 20 consessionnaire partners are involved in activations across 20  events \r\n⦁\tAverage time to market - 30 day average for smaller activities, 90 days for Marquee events\r\n⦁\tExecution excellence - 95% adherance to TAT",
    "supportTeam": "⦁\tBACL, Avishek, Corp Marketing- Apurva, ICT - Jeune\r\n⦁\tAvishek\r\n⦁\tJaveed, Rohan\r\n⦁\tProcurement-Gopi K\r\n⦁\tProcurement-Gopi K",
    "projectDependencies": ""
  },
  {
    "id": "PRADV_13",
    "name": "Convert 300K temp users to active  Pulse Rewards users",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "⦁\tConvert 300K temp users to active  Pulse Rewards users\r\n⦁\tEvents customer aquisition - 10% marketing lead conversion to footfall \r\n⦁\tSocial Media -  30% engagement on an average\r\n⦁\t NPS 80 - activations,  events, landside, advertising\r\n⦁\tLandside guest experience - queue transperancy method",
    "supportTeam": "⦁\tNeeraj, Jeune\r\n⦁\tF&B - Rohan, Neeraj\r\n⦁\tAkash\r\n⦁\tDom",
    "projectDependencies": ""
  },
  {
    "id": "PRADV_15",
    "name": "GPTW - 85% for commercial",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRADV_16",
    "name": "KIAF Funding - 1 Cr",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "⦁\t2% of amount billed to Commercial from all vendors/agencies - 12L\r\n⦁\t2  events X  fundraisers - 1 Cr\r\n⦁\tCO2 saving throught advertsing campaign execution - xxx\r\n⦁\tReducing diesel generator depency xxx",
    "supportTeam": "080-George",
    "projectDependencies": ""
  },
  {
    "id": "PRDF_01",
    "name": "Financials - SPP - 964 (total pax) / IPP 385 (total pax)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_02",
    "name": "Introducing MAC cosmetics",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_03",
    "name": "Introducing new categories (Home appliances)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_04",
    "name": "KIAF donation (collection at Cash counter) - implementation on POS",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_05",
    "name": "PULSE - \"Click & Collect\" - to achieve 10 Cr for FY 26-27",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_06",
    "name": "PULSE - \"Click & Collect\" - Onboarding and maintaining 10 BAs",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_07",
    "name": "Marketing Support on Creatives for monthly campaigns",
    "department": "Duty Free",
    "owner": "Midhun",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_08",
    "name": "NPS - 80",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_09",
    "name": "AI Projects - Passenger led Promos",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_10",
    "name": "AI Projects - Heat Map",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_11",
    "name": "AI Projects - Smart Pricing compared to destination/origin Duty Free",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_12",
    "name": "PULSE Campaigns - DF X Cab Promotion",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_13",
    "name": "PULSE Campaigns - DF X Lounge Access (BASL)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_14",
    "name": "PULSE Campaigns - DF X SPA Access (BASL)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_15",
    "name": "Campaigns for transfer pax  - 9 nos.",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_16",
    "name": "New Store - LMS 2",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_17",
    "name": "New Store - Chanel",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_18",
    "name": "New Store - India Story",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_19",
    "name": "New Store - Tom Ford",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_20",
    "name": "New Store - Coty",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_21",
    "name": "New Store - Dior",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_22",
    "name": "P&C Campaigns - 10 no.s (staff Incentivised)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_23",
    "name": "Taj X Bengaluru DF Collaborated Offer",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_24",
    "name": "Pre-immigration DF / Pulse offer ads (Arr & Dep)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_25",
    "name": "Category Expert Badge & Certification (Motivating staffs)",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_26",
    "name": "DF cross promo Offer with HMS outlets",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_27",
    "name": "DF is now Free Campaign",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRDF_28",
    "name": "FINANCIALS \r\nIPP ..\r\nSPP 817",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "P&C SPP: from 98 --> XXX\r\nArrivals SPP: XXXX --> XXX\r\nDepartures SPP: XXX --> XXXX\r\nTotal SPP : XXX -->\r\nLaunch by April 2026",
    "supportTeam": "Devayani/ Dilpreet\r\nJuene / Samson\r\nSamson\r\nSamson\r\nManoj Swamonathan/ George",
    "projectDependencies": ""
  },
  {
    "id": "PRDF_29",
    "name": "DIGITAL / PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "1. Drive traffic to Pulse & downloads\r\n2. Drive click & collect through Pulse\r\n3. Bonus points redemption factor\r\n4. Attractiveness index\r\n5. Sales support Team for Promoting Pulse Orders (inside DF, LMS, Lounge, Belt Areas)\r\n6. Performance marketing of BLR Pulse - Duty Free\r\n7. Roll-out lucrative Bank / Card Offers \r\n8. Portable Check-out Machine",
    "supportTeam": "Neeraj/ Samson\r\nNeeraj/ Devayani/ Samson\r\nNeeraj\r\nAkash Awasthi\r\nNeeraj\r\nJeune / Neeraj\r\nNeeraj\r\nJeune",
    "projectDependencies": ""
  },
  {
    "id": "PRDF_30",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "kpi": "1. Lacoste Pop Up in Intl Departure \r\n2. Pop - Up in 080 Lounge\r\n3. Swarovski Store\r\n4. Fashion stores (Tumi, Ralph Lauren, Coach)\r\n5. Last minute store (Arrivals)\r\n6. Commercial Master Plan, Vision Document & Business Case\r\n7. LOI from destination sports entertainment like TopGolf/ X-Range & padel/pickle\r\n8. RDE: Retail offerings & pre concept of RDE",
    "supportTeam": "⦁\tDeep/ Deepika\r\n⦁\tGeorge/ Pravat/ Deep\r\n⦁\tPravat/ Deep\r\n⦁\tPravat/ Deep\r\n⦁\tPravat\r\n⦁\tAkash Awasthi\r\n⦁\tSelf\r\n⦁\tRachana",
    "projectDependencies": ""
  },
  {
    "id": "PRDF_31",
    "name": "GPTW - 85% for commercial",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "1. Identify two potential successors for each role directly reporting to the CCO and complete readiness assessments for all identified candidates\r\n2. Establish baseline of the commercial team’s score on ‘openness to challenge and debate’ as measured through Quarterly Pulse Survey and Half-yealy Check-in and set target improvement rate for FY27\r\n3. 100% participation of targeted employees in 12 inspirational learning trips—including airport visits, industry conferences, and global benchmarking experiences—for the commercial team\r\n4. Gender Diversity in Duty Free\r\n5. Diversity & Inclusion Hiring (PRM)\r\n6. Attractive incentive Schemes for the DF team",
    "supportTeam": "⦁\tAll 5 direct reports\r\n⦁\tPeople Partner at Commercial \r\n⦁\t5 direct reports\r\n⦁\tDavid\r\n⦁\tDevayani\r\n⦁\tDavid",
    "projectDependencies": ""
  },
  {
    "id": "PRDF_32",
    "name": "KIAF - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Duty Free",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "1. Raise funds for KIAF by March '26\r\n2. Raise Funds from Donations (5 Rs/bill)\r\n3. LEED certified, recycled & other sustainable initiatives in development of RDE\r\n4. Increase the sale of sustainable products Sale\r\n5. KIA Products sale at Dep Store and Donate X % to KIAF",
    "supportTeam": "David\r\nRachana\r\nRachana\r\nDavid / Samson",
    "projectDependencies": ""
  },
  {
    "id": "PRCBB_01",
    "name": "Travel Concierge",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-07-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCBB_02",
    "name": "PRM Wheel chair ( B2c/B2b)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCBB_03",
    "name": "Paid premuim Buggy",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCBB_04",
    "name": "MHB Baggage Service (B2b/Airline)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCBB_05",
    "name": "Medical Tourism",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRCBB_06",
    "name": "Courier Service ( Excess Baggage)",
    "department": "CBB & Lounge",
    "owner": "Royal Valtrans",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_01",
    "name": "Flexi Space-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_02",
    "name": "Skydeck-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_03",
    "name": "Quad 080 Café- Concpet Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_04",
    "name": "T1 Celebrity Restaurant- Ideation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_05",
    "name": "Habitat-Business Case & Mgt Approval",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_06",
    "name": "SPA Extension In T2 Intl SHA Design Development Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_07",
    "name": "T1 Mezzanine Lounge/F&B- Business Discovery & Mgt Approval Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_08",
    "name": "T2 South Indian Restaurant Kitchen @ Intl SHA Gate Z Café Menu Finalisation & Project Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_09",
    "name": "Urban Consolidation Centre - Central Kitchen / Bakery / Institute Ideation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_10",
    "name": "Forest Of Abundance -Project Execution & Business Evaluation Stage",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "kpi": "",
    "projectDependencies": "",
    "supportTeam": ""
  },
  {
    "id": "PRBASL_11",
    "name": "FINANCIALS\r\nIPP 151\r\nSPP 415",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "kpi": "Penetration 22%\r\nATV INR 2050\r\nHuman capital 69.8 Cr\r\n 40 Crs - 6 non-BLR business (Vision 2030)\r\nEBITDA 25%",
    "supportTeam": "Commercial  BASL / Devayani\r\nRaj Kadamuturu / Darshana BASL Marketing \r\nJoseph Roy\r\nAshish Bakshi/ Pravat Paikray\r\nMuralikrishna Alapati / Chef Pradeep",
    "projectDependencies": ""
  },
  {
    "id": "PRBASL_12",
    "name": "PULSE REWARD\r\n100,000 Active Members\r\nNPS - 80",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "kpi": "100,000 active pulse members\r\nPulse privilege + program by Q1, target 1000 guests\r\n1 Pulse promotion per quarter\r\n2000 member guests - Beyond BLR\r\nImplement Associate recognition program by Q1 - Recognise 30 top performers",
    "supportTeam": "Commercial BASL / Muralikrishna Alapati\r\nRaj Kadamuturu\r\nDarshana BASL Marketing with Devayani & team\r\nAshish Bakshi/ Neeraj Manoria\r\nJoseph Roy/ Muralikrishna Alapati",
    "projectDependencies": ""
  },
  {
    "id": "PRBASL_13",
    "name": "PROCESS\r\nLadies & Gentlemen serve Ladies & Gentlemen",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "kpi": "Associate Empower Program - INR 10K guest experience Q1\r\nTarget 5000 guests annually for WOW experience \r\nInstitutionalise Ladies & Gentlemen service culture by Q3  in F&B, Duty Free & Retail \r\nEstablish Shared services centre for Non- BLR operations by Q1\r\nMultiskill 5% of human capital through utilization of Ai\r\nAutomate B2B & B2C Contract management process turnaorund in  72hrs by Q2",
    "supportTeam": "Joseph Roy/ Muralikrishna Alapati\r\nRaj Kadamuturu\r\nRohan Chaudhury / Joseph Roy / Aarti Naik \r\nMuralikrishna Alapati / Joseph Roy\r\nJoseph Roy / Raj Kadamuturu\r\nBASL Commercial / Ashish / Legal delpartment",
    "projectDependencies": ""
  },
  {
    "id": "PRBASL_14",
    "name": "GPTW - 90% for BASL",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "kpi": "GTPW Certification Q3\r\nCEO Associate chat sessions -12 per year (32 associates per session)\r\nGlobal Conferences - 3, Inspirational Trips - 2",
    "supportTeam": "Joseph Roy \r\nRaj Kadamuturu\r\nAshish Bakshi/ Commercial BASL",
    "projectDependencies": ""
  },
  {
    "id": "PRBASL_15",
    "name": "KIAF - INR 25,00,000\r\nSUSTAINABILITY - 10% reduction in food waste (0.40 gms per dpax)",
    "department": "BASL",
    "owner": "George Kuruvilla",
    "status": "Not Started",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "kpi": "Achieve 1 community  drive per month \r\nReduce waste from 0.47 gms to 0.40 gms per dpax\r\nVendor contribution for KIAF - 10,00,000\r\n1 BASL KIAF awarness campaign per quarter\r\nLEED Certification for non BLR Lounges by Q2",
    "supportTeam": "Joseph Roy\r\nRaj Kadamuturu\r\nMuralikrishna Alapati\r\nCommercial BASL / Devayani\r\nAshish / Kiran Kumar Reddy BASL",
    "projectDependencies": ""
  }
];

export const risks: Risk[] = [
  {
    "id": "RSK-001",
    "projectId": "PRDIGI_01",
    "description": "ABC XYZ",
    "category": "Data/Technical",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-002",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Vendor/External",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-003",
    "projectId": "PRADV_03",
    "description": "ABC XYZ",
    "category": "Data Quality",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-004",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Compliance",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-005",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Governance",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-006",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "People/Culture",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-007",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Compliance",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-008",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Technical",
    "impact": "Medium",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-009",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Resource",
    "impact": "High",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  },
  {
    "id": "RSK-010",
    "projectId": "XXX",
    "description": "ABC XYZ",
    "category": "Adoption",
    "impact": "Low",
    "likelihood": 2,
    "score": 4,
    "severity": "Medium",
    "owner": "",
    "mitigation": "XXX  XXX XXX",
    "status": "Open",
    "targetDate": ""
  }
];

export const departments: Department[] = [
  { name: 'Digital & Data', total: 19, inProgress: 18, completed: 0, notStarted: 1, delayed: 0, critical: 6, pctDone: 0, color: '#5c7cfa' },
  { name: 'Operations', total: 35, inProgress: 22, completed: 0, notStarted: 11, delayed: 2, critical: 6, pctDone: 0, color: '#f59e0b' },
  { name: 'Commercial Development', total: 20, inProgress: 10, completed: 1, notStarted: 9, delayed: 0, critical: 1, pctDone: 5, color: '#10b981' },
  { name: 'Advertising & Marketing', total: 15, inProgress: 2, completed: 0, notStarted: 13, delayed: 0, critical: 0, pctDone: 0, color: '#8b5cf6' },
  { name: 'Duty Free', total: 32, inProgress: 0, completed: 0, notStarted: 32, delayed: 0, critical: 0, pctDone: 0, color: '#f97316' },
  { name: 'CBB & Lounge', total: 6, inProgress: 0, completed: 0, notStarted: 6, delayed: 0, critical: 0, pctDone: 0, color: '#ec4899' },
  { name: 'BASL', total: 15, inProgress: 0, completed: 0, notStarted: 15, delayed: 0, critical: 0, pctDone: 0, color: '#06b6d4' },
];

export const kpiSummary = {
  totalProjects: 142,
  inProgress: 52,
  completed: 1,
  delayed: 2,
  notStarted: 87,
  critical: 13,
  high: 119,
  medium: 5,
  low: 5,
  openRisks: 9,
  stuckProjects: 10,
  needsEscalation: 12,
  ownerBottlenecks: 7,
  totalRisks: 10,
  closedRisks: 1,
  highSeverityOpen: 0,
};

export const riskCategories = ['Data/Technical', 'Vendor/External', 'Data Quality', 'Compliance', 'Governance', 'People/Culture', 'Resource', 'Technical', 'Financial', 'Adoption'];

export const statusOptions = ['In Progress', 'Not Started', 'Completed', 'Delayed', 'On Hold'];
export const priorityOptions = ['Critical', 'High', 'Medium', 'Low'];

export const monthlyTrend = [
  { month: "Apr '26", completed: 1, delayed: 2, inProgress: 40, newProjects: 15 },
  { month: "May '26", completed: 2, delayed: 2, inProgress: 45, newProjects: 12 },
  { month: "Jun '26", completed: 4, delayed: 3, inProgress: 52, newProjects: 18 },
  { month: "Jul '26", completed: 6, delayed: 3, inProgress: 58, newProjects: 10 },
  { month: "Aug '26", completed: 10, delayed: 4, inProgress: 65, newProjects: 14 },
  { month: "Sep '26", completed: 15, delayed: 4, inProgress: 70, newProjects: 10 },
  { month: "Oct '26", completed: 20, delayed: 5, inProgress: 75, newProjects: 12 },
  { month: "Nov '26", completed: 25, delayed: 5, inProgress: 80, newProjects: 8 },
  { month: "Dec '26", completed: 32, delayed: 6, inProgress: 85, newProjects: 5 },
  { month: "Jan '27", completed: 40, delayed: 6, inProgress: 92, newProjects: 15 },
  { month: "Feb '27", completed: 50, delayed: 7, inProgress: 95, newProjects: 10 },
  { month: "Mar '27", completed: 65, delayed: 8, inProgress: 100, newProjects: 20 },
];

export const notifications = [
  { id: 1, title: 'Project Delayed', message: 'PROPR_02: Parking guidance system is now delayed', type: 'warning' as const, time: '2 hours ago', read: false },
  { id: 2, title: 'Risk Escalation', message: 'RSK-004: Compliance gap requires immediate attention', type: 'critical' as const, time: '3 hours ago', read: false },
  { id: 3, title: 'AI Insight', message: 'Digital & Data has 6 critical projects with 0% progress', type: 'insight' as const, time: '5 hours ago', read: false },
  { id: 4, title: 'Milestone Due', message: 'PRDIGI_03: Payment Gateway pilot due May 15', type: 'info' as const, time: '1 day ago', read: true },
  { id: 5, title: 'Owner Bottleneck', message: 'Musthaq Ahamed has 7 active projects assigned', type: 'warning' as const, time: '1 day ago', read: true },
];
