// Auto-generated project data
// Contains all projects and risks for the Enterprise portfolio
// Generated: 2026-06-14T19:45:40.332Z

export interface Allocation {
  id: string;
  type: 'individual' | 'department';
  target: string;
  percentage: number;
}

export interface DetailedDependency {
  id: string;
  targetProjectId?: string;
  description: string;
  allocations: Allocation[];
}

export interface Project {
  id: string;
  name: string;
  department: string;
  owner: string;
  status: 'In Progress' | 'Not Started' | 'Completed' | 'Delayed' | 'On Hold';
  progress: number;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  startDate: string | null;
  targetDate: string | null;
  risks: string;
  objective: string;
  kpi?: string;
  notes: string;
  projectDependencies?: string;
  detailedDependencies?: DetailedDependency[];
  allocations?: Allocation[];
  splitGroupId?: string;
  splitPercentage?: number;
  supportTeam?: string;
  archived?: boolean;
  archivedAt?: string;
  dismissedFromStuck?: boolean;
  financials?: {
    budget: number;
    spent: number;
  };
  tasks?: {
    id: string;
    name: string;
    assignee: string;
    allocations?: Allocation[];
    status: 'Not Started' | 'In Progress' | 'Done';
  }[];
}

export interface Risk {
  id: string;
  projectId: string;
  description: string;
  category: string;
  impact: 'High' | 'Medium' | 'Low';
  likelihood: number;
  score: number;
  severity: string;
  owner: string;
  mitigation: string;
  status: 'Open' | 'Closed';
  targetDate: string;
}

export interface Department {
  name: string;
  total: number;
  inProgress: number;
  completed: number;
  notStarted: number;
  delayed: number;
  critical: number;
  pctDone: number;
  color: string;
}

export const projects: Project[] = [
  {
    "id": "PROPS_1",
    "name": "FINANCIALS \r\nIPP 349\r\nSPP 1278",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_2",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_3",
    "name": "NPS (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Reported on 11th May - NPS is 87.42",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_4",
    "name": "Google Rating (Retail)",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "As on date 4.85",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_5",
    "name": "PULSE - 145K active members",
    "department": "Operations",
    "owner": "Dominic / Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "As on date xxxx",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_6",
    "name": "Highfliers - to be revamped",
    "department": "Operations",
    "owner": "Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "To work on the plan for this FY as per CCO's feedback",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_7",
    "name": "Sustainability - Retail (Green zone)",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Should start by Jun 2026",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_8",
    "name": "ASQ",
    "department": "Operations",
    "owner": "Dominic/Javeed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "ACI has asked for -I commercial survey at departments",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_9",
    "name": "migrated users",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Pending for approval - ?",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_10",
    "name": "XYR recommendations / XYR exclusives - communications & signages",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Pending from marketing team",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_11",
    "name": "Sustainability - Paperless billing",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_1",
    "name": "Store launches - 76 Store Onboarding - 122 (incl of 76)",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_2",
    "name": "Quad 1",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_3",
    "name": "T1 Refurbishment",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-10-15",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_4",
    "name": "ATMS",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-07-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_5",
    "name": "Onboarding and launching of all Pulse / Payment gateway / Loyalty on DAY 0 / EPOS / XYR",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_6",
    "name": "TAT for Tender Process - 60 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_7",
    "name": "TAT for new store fitouts - 100 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_8",
    "name": "TAT for design development - 30 days",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_9",
    "name": "Project Management tool",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_10",
    "name": "Product Development (Water by Blr)",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-01-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_12",
    "name": "GPTW - 85% for commercial",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_13",
    "name": "XYR - 1 cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_1",
    "name": "Advertising SPP XXX (with a turnover of 216Cr - waiting for the number from Debashis)",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_11",
    "name": "MMTH",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-09-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_12",
    "name": "Dining facility @ T2 Basement",
    "department": "Commercial Development",
    "owner": "Pravat / Nikhil",
    "status": "Completed",
    "progress": 100,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_14",
    "name": "Harvest Market",
    "department": "Operations",
    "owner": "Dominic / Javeed",
    "status": "Delayed",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Schedule in place, approval pending from Procurement",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_15",
    "name": "Season Of Smile",
    "department": "Operations",
    "owner": "Dominic/Javeed/Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "Plan to be finalised by Jule 26 end",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_2",
    "name": "Convert 300K temp users to active  Pulse Rewards users",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_3",
    "name": "GPTW - 85% for commercial",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_4",
    "name": "XYR Funding - 1 Cr",
    "department": "Advertising & Marketing",
    "owner": "Devyani",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_13",
    "name": "New product - 20 SKUs across gifting & destination merchandise",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_14",
    "name": "Brand Collaborations",
    "department": "Commercial Development",
    "owner": "Pravat / Jesse",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_15",
    "name": "New Brand Partnership Framework",
    "department": "Commercial Development",
    "owner": "Nikhil Gupta",
    "status": "In Progress",
    "progress": 60,
    "priority": "Critical",
    "startDate": "2026-02-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_16",
    "name": "FINANCIALS \r\nIPP XX\r\nSPP XXX",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_17",
    "name": "PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_18",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_19",
    "name": "GPTW - 85% for commercial",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRCOMDEV_20",
    "name": "XYR - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Commercial Development",
    "owner": "Pravat",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_5",
    "name": "Quad 1 Stage Tender Publish",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_6",
    "name": "Advertising Barricade Branding",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_7",
    "name": "HQ Security Asset Renewal",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_8",
    "name": "Amenities Survey RFQ",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_9",
    "name": "HQ Lobby Gallery Commercial Evaluation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_10",
    "name": "Segmentation Study",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_11",
    "name": "Corporate Division Advertising Strategy",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_12",
    "name": "Recycle Bags Eureka",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_13",
    "name": "Digital Content",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_14",
    "name": "KEMP Football -XYR Framework",
    "department": "Advertising & Marketing",
    "owner": "Ilora/Anindita/Vani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRADMKT_15",
    "name": "P4 Billboard Installation",
    "department": "Advertising & Marketing",
    "owner": "Ilora",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_1",
    "name": "DBS Bank Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with DBS bank and work on points conversion mechanism. DBS members have 20 Cr worth of points",
    "notes": "In principal deal is closed and contract closure by 31st May.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_2",
    "name": "ITC Hotels Integration for rewards points conversion",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Integrate with ITC hotels on rewards poitns conversion and coaliation partnership",
    "notes": "Initial discussion done, proposal is shared and waiting for revert from ITC.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_3",
    "name": "Payment Gateway Enhancement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-05-01",
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "Seasmless Payment experience by resolve all on going issues/Get new partner onboarded",
    "notes": "Pilot with new device will be implemented at DutyFree on 15th May.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_4",
    "name": "Airline partnership for Delayed Passenger Expereince",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Onboard atleast one Airline to enhance delayed passneger expereince by Integrating Airline with Pulse rewards and replace existing coupon and manual F&B model",
    "notes": "Deatiled discussion has been done with AOC and this will need a new product to scan borading pass to enable coupon. This can not be integrated with Pulse due to unavailiability of passenger PI data.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_5",
    "name": "Airline partnership for customer engagement",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "Partner with Airline to enhance customer engagment by curating personalised expereinces and offers to passengers",
    "notes": "Proposal shared with Singapore Airlines and awaiting for their revert, Indigo discussion are at adnaved stage.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_6",
    "name": "CRM for Pulse Rewards Members",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "Build CRM strategies to enhance customer expereince of every rewards member by Launching multiple higher tier member. All CRM initiatives will be targeting expereinces not transactions.",
    "notes": "Proposal is ready to be discussed with leadership team in May, 2026 and finalize.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_7",
    "name": "Gamification on Pusle",
    "department": "Digital & Data",
    "owner": "Musthaq Ahamed",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "Build and launch multiple games on Pulse rewards to engage with Members",
    "notes": "Launched \"Spin the Wheel\" in Pulse. Working on more games.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_8",
    "name": "Retail & Commerce Click and Collect",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "",
    "objective": "Retail & Commerce sales target through PULSE for FY26-27 is ₹8.3Cr. In order to drive this 3X growth, we need to drive as many projects as possible to hit this target",
    "notes": "Programm has started and progress is closely monitored.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_9",
    "name": "Communication Standardisation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "",
    "objective": "Review and revamp the communications architecture flowing our of PULSE to our guest.",
    "notes": "MoEngagae email warmup activity ahs started and shuld be completed by June end.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_10",
    "name": "MoEngage Trigger campaigns",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "",
    "objective": "Identify cross selling and upselling opportunites based on Guest journey flows, through our CDEP Partner platform (Mo Engage)",
    "notes": "Trigger campaigns ongoing, currently working on parking triggers by 20th May, 2026",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_11",
    "name": "Hotel Data Reconciliation",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "We have identified a large mismatch in reported Transit Hotel sales numbers and Actual Sales on ground.",
    "notes": "Recon by May end. On ground SOPs to be conveyed and training to be carried out by May 2026.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_12",
    "name": "CBB Packages",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "Creating digital prepaid CBB++ Packages. Base of the package would be CBB and it can be paired with Lounge/Security Slot booking access/Misc other non-CBB products",
    "notes": "Initial discussion done with GM. Internal meeting to discuss on development of this project.",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_13",
    "name": "Hotels Channel Manager",
    "department": "Digital & Data",
    "owner": "Ajay Rao",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "Automating orders coming from OTAs into the PMS and PULSE DB simultaneously",
    "notes": "Scheduled for Q4",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_14",
    "name": "AI Chatbot for Campus Navigation",
    "department": "Digital & Data",
    "owner": "",
    "status": "In Progress",
    "progress": 35,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_15",
    "name": "FINANCIALS \r\neSPP - 20",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_16",
    "name": "PULSE REWARD\r\n15,00,000 Active Members",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_17",
    "name": "PROCESS\r\nBuilding destination - NPS - 80",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time\r\n\r\nXYRPAY uptime",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_18",
    "name": "GPTW - 85% for commercial",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_19",
    "name": "XYR - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Digital & Data",
    "owner": "Neeraj",
    "status": "In Progress",
    "progress": 35,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_20",
    "name": "CBB - Offline Order Create",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-30",
    "risks": "",
    "objective": "Walkin, B2B, EC Bookings via Pulse Offline order create webhook",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_21",
    "name": "CBB - Kiosk App",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Kiosk and Tablet builds for CBB",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_22",
    "name": "Parking Phase 1",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-09-01",
    "targetDate": "2026-05-31",
    "risks": "",
    "objective": "Parking pre-ordering without status update webhook and without rewards",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_23",
    "name": "Pulse Biz Page Redesign",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-08-31",
    "risks": "",
    "objective": "9 Biz Pages + 72 component pages — App, Mobile, Tablet, Kiosk and Desktop",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_24",
    "name": "Seamless Payment Gateway",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Enhance payment experience and reduce failure rates",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_25",
    "name": "Rewards Integration with Pulse Cart (Including Coupons)",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Unlock rewards coupons and merchant-funded promos",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_26",
    "name": "Pulse Seller Settlement Engine",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Simplify merchant settlement and enable merchant-funded promos",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_27",
    "name": "Pulse Promo Engine",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Enable cross-promotions and cart promotions",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_28",
    "name": "Transit Hotel Channel Manager",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-06-30",
    "risks": "",
    "objective": "Staff portal for offline order creation",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_29",
    "name": "DPDPA Compliance",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2027-01-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "Workshop required to scope product-level changes for DPDPA compliance",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_30",
    "name": "My Booking Refactoring",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-05-31",
    "risks": "",
    "objective": "Upgrade UI and provide all relevant booking information to users",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_31",
    "name": "Pulse Home Page Redesign",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-03-01",
    "targetDate": "2026-07-31",
    "risks": "",
    "objective": "Home Page redesign — App, Mobile, Tablet, Kiosk and Desktop",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_32",
    "name": "Pulse Xclusives",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-10-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "New pre-paid product for Premium Pulse membership — sell bundles combining products and services available on Pulse platform",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_33",
    "name": "CBB - Rewards for non Pulse",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Walkin, B2B, EC Rewards — event based",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_16",
    "name": "P4 Parking: 16mtrs Extension Canopy Tender civil work",
    "department": "Operations",
    "owner": "Raghavendra",
    "status": "In Progress",
    "progress": 30,
    "priority": "Medium",
    "startDate": "2026-03-25",
    "targetDate": "2026-06-05",
    "risks": "",
    "objective": "",
    "notes": "Work is under process - 30% of work completed.\nCapex:  23,05,608",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_17",
    "name": "Relocation of Quad office - Civil & Electrical work",
    "department": "Operations",
    "owner": "Sanjay",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-14",
    "targetDate": "2026-06-05",
    "risks": "",
    "objective": "",
    "notes": "Tendering process in \"On\", To be completed on priority\nCAPEX:  1,37,462",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_18",
    "name": "Rectification/Replacement of Ola/Uber Black Canopy",
    "department": "Operations",
    "owner": "Raghavendra",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-05-04",
    "targetDate": "2026-06-10",
    "risks": "",
    "objective": "",
    "notes": "Tendering process completed, work need to start\nCAPEX:  21,58,220",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_19",
    "name": "P4 Parking Bus Canopy",
    "department": "Operations",
    "owner": "Dominic/Kiran/Raghavendra",
    "status": "In Progress",
    "progress": 30,
    "priority": "Medium",
    "startDate": "2026-03-31",
    "targetDate": "2026-05-31",
    "risks": "",
    "objective": "",
    "notes": "Work is under process - 30% of work completed\nCAPEX:  38,34,686",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_20",
    "name": "BMTC lane and pick up lane on the kerb",
    "department": "Operations",
    "owner": "Dominic/Kiran/Sanjay",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-05-14",
    "targetDate": "2026-08-31",
    "risks": "",
    "objective": "",
    "notes": "Barrication Work is under process -New project\nCAPEX:  2,42,84,474",
    "projectDependencies": ""
  },
  {
    "id": "PRDIGI_34",
    "name": "WhatsApp Commerce",
    "department": "Digital & Data",
    "owner": "Anand Viswanath",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Enable Pulse commerce flows using WhatsApp",
    "notes": "Reporting Manager: Neeraj Manoria",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_21",
    "name": "Namma Yatri final launch",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_22",
    "name": "PULSE REWARD: 7,00,000 Active Members; NPS - 80",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_23",
    "name": "Xyrenis Academy relaunch",
    "department": "Operations",
    "owner": "Javeed/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-01-01",
    "targetDate": "2027-03-31",
    "risks": "",
    "objective": "",
    "notes": "RFQ has been rolled out, go live 11th May.\r\nTechnical eval and new aggreemnt by 30th June.",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_24",
    "name": "Phase wise launch pf Parking guidance system on Pulse",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Delayed",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-05-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_25",
    "name": "ISO final certification process",
    "department": "Operations",
    "owner": "Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": null,
    "targetDate": "2026-09-30",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_26",
    "name": "FSTR by XYR Ordering at Desk",
    "department": "Operations",
    "owner": "Digital owner/ Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-02-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_27",
    "name": "Ground transportation on CBB",
    "department": "Operations",
    "owner": "Ajay / Major",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-04-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_28",
    "name": "XYR Priority access",
    "department": "Operations",
    "owner": "Dominic / George Fanthome",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_29",
    "name": "Construction of additional BMTC zone",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2026-05-26",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_30",
    "name": "Bus canopy construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_31",
    "name": "16m additional zone construction at P4",
    "department": "Operations",
    "owner": "Kiran",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_32",
    "name": "P7 re-designing with BCM exits",
    "department": "Operations",
    "owner": "Dominic / Projects team",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": "2025-11-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_33",
    "name": "MLCP at Alpha 4",
    "department": "Operations",
    "owner": "Dominic",
    "status": "In Progress",
    "progress": 0,
    "priority": "Critical",
    "startDate": "2026-04-01",
    "targetDate": "2026-06-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_34",
    "name": "Fornightly hero products on social media - F&B",
    "department": "Operations",
    "owner": "Rohan / Prashanth",
    "status": "In Progress",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-04-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_35",
    "name": "Fornightly hero products on social media - Retail",
    "department": "Operations",
    "owner": "Javeed / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": "2026-12-01",
    "targetDate": "2027-03-27",
    "risks": "",
    "objective": "",
    "notes": "WIP and go live on 3rd week of May.",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_36",
    "name": "Fornightly hero products on social media - Landside",
    "department": "Operations",
    "owner": "Kiran / Prashanth",
    "status": "Not Started",
    "progress": 0,
    "priority": "Medium",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_37",
    "name": "Shoffer Pilot tracking / results",
    "department": "Operations",
    "owner": "Kiran",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_38",
    "name": "XYR collection at Stores",
    "department": "Operations",
    "owner": "Prashanth / Javeed / Rohan",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "24 Stores are active and collection are in progress.",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_39",
    "name": "Ground trasnportation to be integrated with Pulse",
    "department": "Operations",
    "owner": "Dominic / Neeraj/Devayani",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PROPS_40",
    "name": "Smart Queue Management System",
    "department": "Operations",
    "owner": "Rohan Sharma",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-06-01",
    "targetDate": "2026-12-31",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_1",
    "name": "Financials - SPP - 964 (total users) / IPP 385 (total users)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_2",
    "name": "Introducing MAC cosmetics",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_3",
    "name": "Introducing new categories (Home appliances)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_4",
    "name": "XYR donation (collection at Cash counter) - implementation on POS",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_5",
    "name": "PULSE - \"Click & Collect\" - to achieve 10 Cr for FY 26-27",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_6",
    "name": "PULSE - \"Click & Collect\" - Onboarding and maintaining 10 BAs",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_7",
    "name": "Marketing Support on Creatives for monthly campaigns",
    "department": "Retail & Commerce",
    "owner": "Midhun",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_8",
    "name": "NPS - 80",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_9",
    "name": "AI Projects - Passenger led Promos",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_10",
    "name": "AI Projects - Heat Map",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_11",
    "name": "AI Projects - Smart Pricing compared to destination/origin Retail & Commerce",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_12",
    "name": "PULSE Campaigns - DF X Cab Promotion",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_13",
    "name": "PULSE Campaigns - DF X VIP Access (Strategic Support)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_14",
    "name": "PULSE Campaigns - DF X SPA Access (Strategic Support)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_15",
    "name": "Campaigns for migrated users  - 9 nos.",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_16",
    "name": "New Store - LMS 2",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_17",
    "name": "New Store - Chanel",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_18",
    "name": "New Store - India Story",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_19",
    "name": "New Store - Tom Ford",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_20",
    "name": "New Store - Coty",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_21",
    "name": "New Store - Dior",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_22",
    "name": "P&C Campaigns - 10 no.s (staff Incentivised)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_23",
    "name": "Taj X Bengaluru DF Collaborated Offer",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_24",
    "name": "Pre-immigration DF / Pulse offer ads (Arr & Dep)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_25",
    "name": "Category Expert Badge & Certification (Motivating staffs)",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_26",
    "name": "DF cross promo Offer with HMS outlets",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_27",
    "name": "DF is now Free Campaign",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_28",
    "name": "FINANCIALS \r\nIPP ..\r\nSPP 817",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_29",
    "name": "DIGITAL / PULSE REWARD\r\n15,00,000 Active Members\r\nNPS - 80",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_30",
    "name": "PROCESS\r\nBuilding destination",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_31",
    "name": "GPTW - 85% for commercial",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRRETAIL_32",
    "name": "XYR - 2 Cr\r\nSUSTAINABILITY -5000 tons of CO2 saving",
    "department": "Retail & Commerce",
    "owner": "Avishek",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_1",
    "name": "Flexi Space-Business Case & Mgt Approval",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_2",
    "name": "Skydeck-Business Case & Mgt Approval",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_3",
    "name": "Quad 080 Café- Concpet Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_4",
    "name": "T1 Celebrity Restaurant- Ideation Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_5",
    "name": "Habitat-Business Case & Mgt Approval",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_6",
    "name": "SPA Extension In T2 Intl SHA Design Development Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_7",
    "name": "East Wing Mezzanine Lounge/F&B- Business Discovery & Mgt Approval Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_8",
    "name": "West Wing Indian Restaurant Kitchen @ Building B Main Floor Café Menu Finalisation & Project Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_9",
    "name": "Urban Consolidation Centre - Central Kitchen / Bakery / Institute Ideation Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_10",
    "name": "Forest Of Abundance -Project Execution & Business Evaluation Stage",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "High",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_11",
    "name": "FINANCIALS\r\nIPP 151\r\nSPP 415",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Drive growth in experience economy by enhancing per capita sales",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_12",
    "name": "PULSE REWARD\r\n100,000 Active Members\r\nNPS - 80",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Elevate end-to-end guest experience across touchpoints",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_13",
    "name": "PROCESS\r\nLadies & Gentlemen serve Ladies & Gentlemen",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Achieve process excellence by streamlining key operational workflows to improve turnaround time",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_14",
    "name": "GPTW - 90% for Strategic Support",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a High-Performance culture in a Future-Ready, Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRSTRAT_15",
    "name": "XYR - INR 25,00,000\r\nSUSTAINABILITY - 10% reduction in food waste (0.40 gms per user)",
    "department": "Strategic Support",
    "owner": "George Kuruvilla",
    "status": "In Progress",
    "progress": 0,
    "priority": "Low",
    "startDate": null,
    "targetDate": "2027-03-01",
    "risks": "",
    "objective": "Build a Responsible, Sustainable Organization",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_1",
    "name": "PRM Wheel chair ( B2c/B2b)",
    "department": "CBB",
    "owner": "Noel/Pradip",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_2",
    "name": "Paid premuim Buggy",
    "department": "CBB",
    "owner": "Noel",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_3",
    "name": "MHB Baggage Service (B2b/Airline)",
    "department": "CBB",
    "owner": "Noel/Pradip",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-08-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_4",
    "name": "Medical Tourism",
    "department": "CBB",
    "owner": "Noel",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_5",
    "name": "Courier Service ( Excess Baggage)",
    "department": "CBB",
    "owner": "Noel/Pradip",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-12-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_6",
    "name": "Travel Concierge",
    "department": "CBB",
    "owner": "Noel",
    "status": "Not Started",
    "progress": 0,
    "priority": "High",
    "startDate": "2026-07-01",
    "targetDate": null,
    "risks": "",
    "objective": "",
    "notes": "",
    "projectDependencies": ""
  },
  {
    "id": "PRAMEN_7",
    "name": "Lounge Automation Phase 2",
    "department": "CBB",
    "owner": "System",
    "status": "In Progress",
    "progress": 50,
    "priority": "Medium",
    "startDate": null,
    "targetDate": null,
    "risks": "",
    "objective": "Complete automation rollout",
    "notes": "Restored sequence",
    "projectDependencies": ""
  }
];

export const risks: Risk[] = [];

export const departments: Department[] = [
  { name: 'Digital & Data', total: 19, inProgress: 18, completed: 0, notStarted: 1, delayed: 0, critical: 6, pctDone: 0, color: '#5c7cfa' },
  { name: 'Operations', total: 35, inProgress: 22, completed: 0, notStarted: 11, delayed: 2, critical: 6, pctDone: 0, color: '#f59e0b' },
  { name: 'Commercial Development', total: 20, inProgress: 10, completed: 1, notStarted: 9, delayed: 0, critical: 1, pctDone: 5, color: '#10b981' },
  { name: 'Advertising & Marketing', total: 15, inProgress: 2, completed: 0, notStarted: 13, delayed: 0, critical: 0, pctDone: 0, color: '#8b5cf6' },
  { name: 'Retail & Commerce', total: 32, inProgress: 0, completed: 0, notStarted: 32, delayed: 0, critical: 0, pctDone: 0, color: '#f97316' },
  { name: 'CBB', total: 6, inProgress: 0, completed: 0, notStarted: 6, delayed: 0, critical: 0, pctDone: 0, color: '#ec4899' },
  { name: 'Strategic Support', total: 15, inProgress: 0, completed: 0, notStarted: 15, delayed: 0, critical: 0, pctDone: 0, color: '#06b6d4' },
];
export const kpiSummary = {
  totalProjects: 162,
  inProgress: 92,
  completed: 1,
  delayed: 2,
  notStarted: 67,
  critical: 13,
  high: 134,

  medium: 10,
  low: 5,
  openRisks: 0,
  highSeverityRisks: 0,
};

export const riskCategories = ['Data/Technical', 'Vendor/External', 'Data Quality', 'Compliance', 'Governance', 'People/Culture', 'Resource', 'Technical', 'Financial', 'Adoption'];

export const statusOptions = ['In Progress', 'Not Started', 'Completed', 'Delayed', 'On Hold'];
export const priorityOptions = ['Critical', 'High', 'Medium', 'Low'];

export const monthlyTrend = [
  { month: 'Oct', completed: 0, delayed: 0, inProgress: 28, newProjects: 12 },
  { month: 'Nov', completed: 0, delayed: 0, inProgress: 35, newProjects: 8 },
  { month: 'Dec', completed: 0, delayed: 1, inProgress: 38, newProjects: 5 },
  { month: 'Jan', completed: 0, delayed: 1, inProgress: 42, newProjects: 15 },
  { month: 'Feb', completed: 0, delayed: 1, inProgress: 45, newProjects: 10 },
  { month: 'Mar', completed: 1, delayed: 2, inProgress: 48, newProjects: 20 },
  { month: 'Apr', completed: 1, delayed: 2, inProgress: 50, newProjects: 18 },
  { month: 'May', completed: 1, delayed: 2, inProgress: 52, newProjects: 14 },
];

export const notifications = [
  { id: 1, title: 'Project Delayed', message: 'PROPR_02: Parking guidance system is now delayed', type: 'warning' as const, time: '2 hours ago', read: false },
  { id: 2, title: 'Risk Escalation', message: 'RSK-004: Compliance gap requires immediate attention', type: 'critical' as const, time: '3 hours ago', read: false },
  { id: 3, title: 'AI Insight', message: 'Digital & Data has 6 critical projects with 0% progress', type: 'insight' as const, time: '5 hours ago', read: false },
  { id: 4, title: 'Milestone Due', message: 'PRDIGI_03: Payment Gateway pilot due May 15', type: 'info' as const, time: '1 day ago', read: true },
  { id: 5, title: 'Owner Bottleneck', message: 'Musthaq Ahamed has 7 active projects assigned', type: 'warning' as const, time: '1 day ago', read: true },
];
